# Generated by Django 4.2.3 on 2023-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('source_app', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('sender_message', models.TextField(blank=True, null=True)),
                ('is_test', models.BooleanField()),
            ],
        ),
    ]
